# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0002_auto_20171020_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
