# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0004_auto_20171116_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.CharField(blank=True, default='No feedback yet', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, default='No grade yet', max_length=100, null=True),
        ),
    ]
