# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0005_profile_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
